const vehicles = [
  { brand: "BYD", name: "Shark (皮卡)", fob: "$55,200 – $59,500", battery: "29.6 kWh", batteryType: "LFP (PHEV)", range: "840 km (Ext)", charging: "[2025 Global Spotlight] DMO off-road platform — high-power V2L export + 1,000 km+ range · 50–60% fuel savings", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/shark/shark%20display.png", status: "factory", statusText: "Factory Order: 21 Days", link: "/products/utility-pro/byd-shark", tags: ["Pickup Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "Above $35,000", "V2L Power Export", "4WD / AWD", "High Clearance (200mm+)", "Factory Order (18+ Days)"] },
  { brand: "Radar", name: "RD6 (雷达)", fob: "$20,800 – $38,400", battery: "86.0 kWh", batteryType: "LFP", range: "520 km", charging: "6 kW V2L + SUV-grade comfort + large frunk — operating cost only 1/5 of diesel pickup", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/RD6/RD6%20display.webp", status: "in-stock", statusText: "In Stock: Hangzhou", link: "/products/utility-pro/radar-rd6", tags: ["Pickup Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "Above $35,000", "V2L Power Export", "In Stock (Port)"] },
  { brand: "GWM", name: "Cannon EV (山海炮)", fob: "$32,700 – $44,100", battery: "37.1 kWh", batteryType: "NCM (HEV/PHEV)", range: "1,000 km (Ext)", charging: "Tank chassis + ultra-rugged body + proven off-road · extremely reliable in harsh conditions · stellar overseas rep", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/cannonev/cannonev%20display.jpg", status: "factory", statusText: "Factory Order: 28 Days", link: "/products/utility-pro/gwm-cannon-ev", tags: ["Pickup Truck", "NCM (Ternary Lithium)", "350 km +", "Above $35,000", "4WD / AWD", "High Clearance (200mm+)", "Factory Order (18+ Days)"] },
  { brand: "Farizon", name: "Super Van", fob: "$27,100 – $37,100", battery: "66.0 kWh", batteryType: "LFP", range: "350 km", charging: "[2025 Digital Cargo] Geely Farizon flagship — steer-by-wire + flat floor + max cargo bay · +20% space efficiency", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/supervan/supervan%20display.png", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/utility-pro/farizon-super-van", tags: ["Cargo Van", "LFP (Lithium Iron Phosphate)", "350 km +", "$20,000 - $35,000", "In Stock (Port)"] },
  { brand: "Farizon", name: "Xingxiang V", fob: "$14,800 – $19,500", battery: "41.9 kWh", batteryType: "LFP", range: "260 km", charging: "Farizon urban delivery champ — 6 m³ cargo + near-zero failure rate + mature aftersales · saves $350–$500/mo", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/xingxiangv/xingxiangv%20display.webp", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/utility-pro/farizon-xingxiang-v", tags: ["Cargo Van", "LFP (Lithium Iron Phosphate)", "250 km - 350 km", "$20,000 - $35,000", "In Stock (Port)"] },
  { brand: "BYD", name: "T5 (纯电轻卡)", fob: "$23,300 – $24,700", battery: "85.0 kWh", batteryType: "LFP Blade", range: "275 km", charging: "Built for bulk urban delivery — Blade Battery + reinforced frame + super fast charge · saves $600+/mo", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/T5/T5%20display.webp", status: "factory", statusText: "Factory Order: 21 Days", link: "/products/utility-pro/byd-t5", tags: ["Micro Truck", "LFP (Lithium Iron Phosphate)", "250 km - 350 km", "$20,000 - $35,000", "Factory Order (18+ Days)"] },
  { brand: "Maxus", name: "eDeliver 9", fob: "$34,300 – $41,400", battery: "88.5 kWh", batteryType: "LFP / NCM", range: "353 km", charging: "Maxus flagship EV van — 11 m³ cargo space + top safety rating + EU & Australia export veteran", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/edeliver/edeliver9%20display.jpg", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/utility-pro/maxus-edeliver-9", tags: ["Cargo Van", "LFP (Lithium Iron Phosphate)", "350 km +", "Above $35,000", "In Stock (Port)"] },
  { brand: "Dongfeng", name: "Rich 6 EV", fob: "$20,700 – $28,500", battery: "68.8 kWh", batteryType: "LFP", range: "350 km", charging: "Classic rugged EV pickup — Nissan Navara platform + high clearance + mature powertrain · ultra-low mining failure rate", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/rich6ev/rich6ev%20display.jpg", status: "in-stock", statusText: "In Stock: Wuhan", link: "/products/utility-pro/dongfeng-rich-6-ev", tags: ["Pickup Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "$20,000 - $35,000", "High Clearance (200mm+)", "In Stock (Port)"] },
  { brand: "Tank", name: "500 Hi4-T", fob: "$47,900 – $56,400", battery: "37.1 kWh", batteryType: "NCM (PHEV)", range: "790 km (Ext)", charging: "Hardcore off-road PHEV — mechanical 4WD + luxury interior + extreme recovery · city EV / long-range overland", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/Hi4-T/Hi4-T%20display.jpg", status: "factory", statusText: "Factory Order: 28 Days", link: "/products/utility-pro/tank-500-hi4t", tags: ["Pickup Truck", "NCM (Ternary Lithium)", "350 km +", "Above $35,000", "4WD / AWD", "High Clearance (200mm+)", "Factory Order (18+ Days)"] },
  { brand: "Foton", name: "eAumark (福田)", fob: "$24,100 – $32,700", battery: "106.9 kWh", batteryType: "LFP", range: "400 km", charging: "Global light-truck leader — modular chassis + high-efficiency e-axle + remote monitoring · ideal for cold-chain & special builds", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/eaumark/eaumark%20display.jpg", status: "factory", statusText: "Factory Order: 30 Days", link: "/products/utility-pro/foton-eaumark", tags: ["Micro Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "$20,000 - $35,000", "Factory Order (18+ Days)"] },
];

const specLabels: Record<string, string> = {
  "29.6 kWh": "Battery", "86.0 kWh": "Battery", "37.1 kWh": "Battery", "66.0 kWh": "Battery", "41.9 kWh": "Battery", "85.0 kWh": "Battery", "88.5 kWh": "Battery", "68.8 kWh": "Battery", "106.9 kWh": "Battery",
  "840 km (Ext)": "Range (Extended)", "520 km": "Range (NEDC)", "1,000 km (Ext)": "Range (Extended)", "350 km": "Range (NEDC)", "260 km": "Range (NEDC)", "275 km": "Range (NEDC)", "353 km": "Range (NEDC)", "790 km (Ext)": "Range (Extended)", "400 km": "Range (NEDC)",
  "[2025 Global Spotlight] DMO off-road platform — high-power V2L export + 1,000 km+ range · 50–60% fuel savings": "Buyer Logic",
  "6 kW V2L + SUV-grade comfort + large frunk — operating cost only 1/5 of diesel pickup": "Buyer Logic",
  "Tank chassis + ultra-rugged body + proven off-road · extremely reliable in harsh conditions · stellar overseas rep": "Buyer Logic",
  "[2025 Digital Cargo] Geely Farizon flagship — steer-by-wire + flat floor + max cargo bay · +20% space efficiency": "Buyer Logic",
  "Farizon urban delivery champ — 6 m³ cargo + near-zero failure rate + mature aftersales · saves $350–$500/mo": "Buyer Logic",
  "Built for bulk urban delivery — Blade Battery + reinforced frame + super fast charge · saves $600+/mo": "Buyer Logic",
  "Maxus flagship EV van — 11 m³ cargo space + top safety rating + EU & Australia export veteran": "Buyer Logic",
  "Classic rugged EV pickup — Nissan Navara platform + high clearance + mature powertrain · ultra-low mining failure rate": "Buyer Logic",
  "Hardcore off-road PHEV — mechanical 4WD + luxury interior + extreme recovery · city EV / long-range overland": "Buyer Logic",
  "Global light-truck leader — modular chassis + high-efficiency e-axle + remote monitoring · ideal for cold-chain & special builds": "Buyer Logic",
};

export { vehicles, specLabels };
