const vehicles = [
  {
    brand: "BYD",
    name: "Shark (皮卡)",
    fob: "¥386,600 – 416,500 (Overseas)",
    battery: "29.6 kWh",
    batteryType: "LFP (PHEV)",
    range: "840 km (Ext)",
    charging: "[2025 Global Spotlight] DMO off-road platform — high-power V2L export + 1,000 km+ range · 50–60% fuel savings",
    img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 21 Days",
    tags: ["Pickup Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "Above ¥250,000", "V2L Power Export", "4WD / AWD", "High Clearance (200mm+)", "Factory Order (18+ Days)"],
  },
  {
    brand: "Radar",
    name: "RD6 (雷达)",
    fob: "¥145,800 – 268,800",
    battery: "86.0 kWh",
    batteryType: "LFP",
    range: "520 km",
    charging: "6 kW V2L + SUV-grade comfort + large frunk — operating cost only 1/5 of diesel pickup",
    img: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Hangzhou",
    tags: ["Pickup Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "Above ¥250,000", "V2L Power Export", "In Stock (Port)"],
  },
  {
    brand: "GWM",
    name: "Cannon EV (山海炮)",
    fob: "¥228,800 – 308,800",
    battery: "37.1 kWh",
    batteryType: "NCM (HEV/PHEV)",
    range: "1,000 km (Ext)",
    charging: "Tank chassis + ultra-rugged body + proven off-road · extremely reliable in harsh conditions · stellar overseas rep",
    img: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 28 Days",
    tags: ["Pickup Truck", "NCM (Ternary Lithium)", "350 km +", "Above ¥250,000", "4WD / AWD", "High Clearance (200mm+)", "Factory Order (18+ Days)"],
  },
  {
    brand: "Farizon",
    name: "Super Van",
    fob: "¥189,800 – 259,800",
    battery: "66.0 kWh",
    batteryType: "LFP",
    range: "350 km",
    charging: "[2025 Digital Cargo] Geely Farizon flagship — steer-by-wire + flat floor + max cargo bay · +20% space efficiency",
    img: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Shanghai",
    tags: ["Cargo Van", "LFP (Lithium Iron Phosphate)", "350 km +", "¥150,000 - ¥250,000", "In Stock (Port)"],
  },
  {
    brand: "Farizon",
    name: "Xingxiang V",
    fob: "¥103,800 – 136,800",
    battery: "41.9 kWh",
    batteryType: "LFP",
    range: "260 km",
    charging: "Farizon urban delivery champ — 6 m³ cargo + near-zero failure rate + mature aftersales · saves $350–$500/mo",
    img: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Shanghai",
    tags: ["Cargo Van", "LFP (Lithium Iron Phosphate)", "250 km - 350 km", "¥150,000 - ¥250,000", "In Stock (Port)"],
  },
  {
    brand: "BYD",
    name: "T5 (纯电轻卡)",
    fob: "¥162,800 – 172,800",
    battery: "85.0 kWh",
    batteryType: "LFP Blade",
    range: "275 km",
    charging: "Built for bulk urban delivery — Blade Battery + reinforced frame + super fast charge · saves $600+/mo",
    img: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 21 Days",
    tags: ["Micro Truck", "LFP (Lithium Iron Phosphate)", "250 km - 350 km", "¥150,000 - ¥250,000", "Factory Order (18+ Days)"],
  },
  {
    brand: "Maxus",
    name: "eDeliver 9",
    fob: "¥239,800 – 289,800",
    battery: "88.5 kWh",
    batteryType: "LFP / NCM",
    range: "353 km",
    charging: "Maxus flagship EV van — 11 m³ cargo space + top safety rating + EU & Australia export veteran",
    img: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Shanghai",
    tags: ["Cargo Van", "LFP (Lithium Iron Phosphate)", "350 km +", "Above ¥250,000", "In Stock (Port)"],
  },
  {
    brand: "Dongfeng",
    name: "Rich 6 EV",
    fob: "¥144,800 – 199,800",
    battery: "68.8 kWh",
    batteryType: "LFP",
    range: "350 km",
    charging: "Classic rugged EV pickup — Nissan Navara platform + high clearance + mature powertrain · ultra-low mining failure rate",
    img: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Wuhan",
    tags: ["Pickup Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "¥150,000 - ¥250,000", "High Clearance (200mm+)", "In Stock (Port)"],
  },
  {
    brand: "Tank",
    name: "500 Hi4-T",
    fob: "¥335,000 – 395,000",
    battery: "37.1 kWh",
    batteryType: "NCM (PHEV)",
    range: "790 km (Ext)",
    charging: "Hardcore off-road PHEV — mechanical 4WD + luxury interior + extreme recovery · city EV / long-range overland",
    img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 28 Days",
    tags: ["Pickup Truck", "NCM (Ternary Lithium)", "350 km +", "Above ¥250,000", "4WD / AWD", "High Clearance (200mm+)", "Factory Order (18+ Days)"],
  },
  {
    brand: "Foton",
    name: "eAumark (福田)",
    fob: "¥168,800 – 228,800",
    battery: "106.9 kWh",
    batteryType: "LFP",
    range: "400 km",
    charging: "Global light-truck leader — modular chassis + high-efficiency e-axle + remote monitoring · ideal for cold-chain & special builds",
    img: "https://images.unsplash.com/photo-1563720360172-67b8f3dce741?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 30 Days",
    tags: ["Micro Truck", "LFP (Lithium Iron Phosphate)", "350 km +", "¥150,000 - ¥250,000", "Factory Order (18+ Days)"],
  },
];

const specLabels: Record<string, string> = {
  "29.6 kWh": "Battery",
  "86.0 kWh": "Battery",
  "37.1 kWh": "Battery",
  "66.0 kWh": "Battery",
  "41.9 kWh": "Battery",
  "85.0 kWh": "Battery",
  "88.5 kWh": "Battery",
  "68.8 kWh": "Battery",
  "106.9 kWh": "Battery",
  "840 km (Ext)": "Range (Extended)",
  "520 km": "Range (NEDC)",
  "1,000 km (Ext)": "Range (Extended)",
  "350 km": "Range (NEDC)",
  "260 km": "Range (NEDC)",
  "275 km": "Range (NEDC)",
  "353 km": "Range (NEDC)",
  "790 km (Ext)": "Range (Extended)",
  "400 km": "Range (NEDC)",
  "[2025 Global Spotlight] DMO off-road platform — high-power V2L export + 1,000 km+ range · 50–60% fuel savings": "Buyer Logic",
  "6 kW V2L + SUV-grade comfort + large frunk — operating cost only 1/5 of diesel pickup": "Buyer Logic",
  "Tank chassis + ultra-rugged body + proven off-road · extremely reliable in harsh conditions · stellar overseas rep": "Buyer Logic",
  "[2025 Digital Cargo] Geely Farizon flagship — steer-by-wire + flat floor + max cargo bay · +20% space efficiency": "Buyer Logic",
  "Farizon urban delivery champ — 6 m³ cargo + near-zero failure rate + mature aftersales · saves $350–$500/mo": "Buyer Logic",
  "Built for bulk urban delivery — Blade Battery + reinforced frame + super fast charge · saves $600+/mo": "Buyer Logic",
  "Maxus flagship EV van — 11 m³ cargo space + top safety rating + EU & Australia export veteran": "Buyer Logic",
  "Classic rugged EV pickup — Nissan Navara platform + high clearance + mature powertrain · ultra-low mining failure rate": "Buyer Logic",
  "Hardcore off-road PHEV — mechanical 4WD + luxury interior + extreme recovery · city EV / long-range overland": "Buyer Logic",
  "Global light-truck leader — modular chassis + high-efficiency e-axle + remote monitoring · ideal for cold-chain & special builds": "Buyer Logic",
};

export { vehicles, specLabels };
