const vehicles = [
  { brand: "BYD", name: "Seagull (海鸥)", fob: "CNY 69,800 – 85,900", battery: "38.8 kWh", batteryType: "LFP Blade", range: "405 km", charging: "Global #1 commuter — Blade Battery + rotating touchscreen + mature 3-electric system", img: "https://images.unsplash.com/photo-1620800615569-42b781a62dcb?auto=format&fit=crop&w=800&q=80", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/revenue-king/byd-seagull", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Under CNY 100,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "BYD", name: "Dolphin (海豚)", fob: "CNY 99,800 – 129,800", battery: "44.9 kWh", batteryType: "LFP Blade", range: "420 km", charging: "2025 comfort suspension — e-Platform 3.0 + heat pump across all trims", img: "https://images.unsplash.com/photo-1563720360172-67b8f3dce741?auto=format&fit=crop&w=800&q=80", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/revenue-king/byd-dolphin", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "CNY 100,000 - CNY 150,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "BYD", name: "Qin PLUS EV", fob: "CNY 119,800 – 139,800", battery: "57.6 kWh", batteryType: "LFP Blade", range: "510 km", charging: "1M+ units validated — ultra-low drag + large boot + lowest after-sales costs", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/2qin-plus-ev-p.webp", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/revenue-king/byd-qin-plus", tags: ["Sedan", "LFP (Lithium Iron Phosphate)", "450 km +", "CNY 100,000 - CNY 150,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "GAC Aion", name: "RT (迅猛龙)", fob: "CNY 99,800 – 165,800", battery: "55.1 kWh", batteryType: "LFP", range: "520 km", charging: "[2025 New King] LiDAR smart driving + executive rear legroom + 400V fast charge", img: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=800&q=80", status: "factory", statusText: "Factory Order: 14 Days", link: "/products/revenue-king/gac-aion-rt", tags: ["Sedan", "LFP (Lithium Iron Phosphate)", "450 km +", "Above CNY 150,000", "LHD (Left-Hand Drive)", "Factory Order (14+ Days)"] },
  { brand: "Geely", name: "Galaxy E5", fob: "CNY 109,800 – 145,800", battery: "60.0 kWh", batteryType: "LFP", range: "530 km", charging: "[Battle-Tested] Shield Short-Blade battery + Galaxy OS + global safety design", img: "https://images.unsplash.com/photo-1542362567-b052d00122e2?auto=format&fit=crop&w=800&q=80", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/revenue-king/geely-galaxy-e5", tags: ["Compact SUV", "LFP (Lithium Iron Phosphate)", "450 km +", "CNY 100,000 - CNY 150,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "GAC Motor", name: "Aion Y Plus", fob: "CNY 99,800 – 159,800", battery: "51.9 kWh", batteryType: "LFP", range: "430 km", charging: "Box design + wide-opening doors + camping-friendly", img: "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?auto=format&fit=crop&w=800&q=80", status: "in-stock", statusText: "In Stock: Guangzhou", link: "/products/revenue-king/gac-aion-y-plus", tags: ["Compact SUV", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Above CNY 150,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Wuling", name: "Bingo Plus", fob: "CNY 89,800 – 98,800", battery: "37.9 kWh", batteryType: "LFP", range: "510 km", charging: "Retro design + 510 km range + effortless driving", img: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80", status: "in-stock", statusText: "In Stock: Liuzhou", link: "/products/revenue-king/wuling-bingo-plus", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "450 km +", "Under CNY 100,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Changan", name: "Lumin", fob: "CNY 37,900 – 61,900", battery: "27.9 kWh", batteryType: "LFP", range: "301 km", charging: "Premium quality at entry price — high-strength steel + flexible charging", img: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80", status: "in-stock", statusText: "In Stock: Chongqing", link: "/products/revenue-king/changan-lumin", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Under CNY 100,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Geely", name: "Geometry C", fob: "CNY 129,800 – 159,800", battery: "70.0 kWh", batteryType: "LFP", range: "550 km", charging: "ME bestseller — exceptional real-world range + extreme heat optimised", img: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/revenue-king/geely-geometry-c", tags: ["Compact SUV", "LFP (Lithium Iron Phosphate)", "450 km +", "Above CNY 150,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Leapmotor", name: "T03", fob: "CNY 49,900 – 69,900", battery: "41.3 kWh", batteryType: "LFP", range: "403 km", charging: "Stellantis-backed + European standards + dual 8\"+10\" screens", img: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80", status: "factory", statusText: "Factory Order: 14 Days", link: "/products/revenue-king/leapmotor-t03", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Under CNY 100,000", "LHD (Left-Hand Drive)", "Factory Order (14+ Days)"] },
];

const specLabels: Record<string, string> = {
  "38.8 kWh": "Battery", "44.9 kWh": "Battery", "57.6 kWh": "Battery", "55.1 kWh": "Battery", "60.0 kWh": "Battery", "51.9 kWh": "Battery", "37.9 kWh": "Battery", "27.9 kWh": "Battery", "70.0 kWh": "Battery", "41.3 kWh": "Battery",
  "405 km": "Range (NEDC)", "420 km": "Range (NEDC)", "510 km": "Range (NEDC)", "520 km": "Range (NEDC)", "530 km": "Range (NEDC)", "430 km": "Range (NEDC)", "301 km": "Range (NEDC)", "550 km": "Range (NEDC)", "403 km": "Range (NEDC)",
  "Global #1 commuter — Blade Battery + rotating touchscreen + mature 3-electric system": "Buyer Logic",
  "2025 comfort suspension — e-Platform 3.0 + heat pump across all trims": "Buyer Logic",
  "1M+ units validated — ultra-low drag + large boot + lowest after-sales costs": "Buyer Logic",
  "[2025 New King] LiDAR smart driving + executive rear legroom + 400V fast charge": "Buyer Logic",
  "[Battle-Tested] Shield Short-Blade battery + Galaxy OS + global safety design": "Buyer Logic",
  "Box design + wide-opening doors + camping-friendly": "Buyer Logic",
  "Retro design + 510 km range + effortless driving": "Buyer Logic",
  "Premium quality at entry price — high-strength steel + flexible charging": "Buyer Logic",
  "ME bestseller — exceptional real-world range + extreme heat optimised": "Buyer Logic",
  "Stellantis-backed + European standards + dual 8\"+10\" screens": "Buyer Logic",
};

export { vehicles, specLabels };
