const vehicles = [
  { brand: "BYD", name: "Seagull", fob: "$10,000 – $12,300", battery: "38.8 kWh", batteryType: "LFP Blade", range: "405 km", charging: "Global #1 commuter — Blade Battery + rotating touchscreen + mature 3-electric system", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/seagull/seagull%20display.png", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/revenue-king/byd-seagull", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Under $15,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "BYD", name: "Dolphin", fob: "$14,300 – $18,500", battery: "44.9 kWh", batteryType: "LFP Blade", range: "420 km", charging: "2025 comfort suspension — e-Platform 3.0 + heat pump across all trims", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/dolphin/dolphin%20display.webp", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/revenue-king/byd-dolphin", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "$15,000 - $20,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "BYD", name: "Qin PLUS EV", fob: "$17,100 – $20,000", battery: "57.6 kWh", batteryType: "LFP Blade", range: "510 km", charging: "1M+ units validated — ultra-low drag + large boot + lowest after-sales costs", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/qinplusev/qinplusev%20display.webp", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/revenue-king/byd-qin-plus", tags: ["Sedan", "LFP (Lithium Iron Phosphate)", "450 km +", "$15,000 - $20,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "GAC Aion", name: "RT", fob: "$14,300 – $23,700", battery: "55.1 kWh", batteryType: "LFP", range: "520 km", charging: "[2025 New King] LiDAR smart driving + executive rear legroom + 400V fast charge", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/RT/RT%20display.jpg", status: "factory", statusText: "Factory Order: 14 Days", link: "/products/revenue-king/gac-aion-rt", tags: ["Sedan", "LFP (Lithium Iron Phosphate)", "450 km +", "Above $20,000", "LHD (Left-Hand Drive)", "Factory Order (14+ Days)"] },
  { brand: "Geely", name: "Galaxy E5", fob: "$15,700 – $20,800", battery: "60.0 kWh", batteryType: "LFP", range: "530 km", charging: "[Battle-Tested] Shield Short-Blade battery + Galaxy OS + global safety design", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/Galaxye5/Galaxye5%20display.jpg", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/revenue-king/geely-galaxy-e5", tags: ["Compact SUV", "LFP (Lithium Iron Phosphate)", "450 km +", "$15,000 - $20,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "GAC Motor", name: "Aion Y Plus", fob: "$14,300 – $22,800", battery: "51.9 kWh", batteryType: "LFP", range: "430 km", charging: "Box design + wide-opening doors + camping-friendly", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/T03/Yplus%20display.jpg", status: "in-stock", statusText: "In Stock: Guangzhou", link: "/products/revenue-king/gac-aion-y-plus", tags: ["Compact SUV", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Above $20,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Wuling", name: "Bingo Plus", fob: "$12,800 – $14,100", battery: "37.9 kWh", batteryType: "LFP", range: "510 km", charging: "Retro design + 510 km range + effortless driving", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/bingoplus/bingoplus%20display.jpg", status: "in-stock", statusText: "In Stock: Liuzhou", link: "/products/revenue-king/wuling-bingo-plus", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "450 km +", "Under $15,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Changan", name: "Lumin", fob: "$5,400 – $8,800", battery: "27.9 kWh", batteryType: "LFP", range: "301 km", charging: "Premium quality at entry price — high-strength steel + flexible charging", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/lumin/lumin%20display.jpg", status: "in-stock", statusText: "In Stock: Chongqing", link: "/products/revenue-king/changan-lumin", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Under $15,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Geely", name: "Geometry C", fob: "$18,500 – $22,800", battery: "70.0 kWh", batteryType: "LFP", range: "550 km", charging: "ME bestseller — exceptional real-world range + extreme heat optimised", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/geometryc/geometryc%20display.jpg", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/revenue-king/geely-geometry-c", tags: ["Compact SUV", "LFP (Lithium Iron Phosphate)", "450 km +", "Above $20,000", "LHD (Left-Hand Drive)", "In Stock (Port)"] },
  { brand: "Leapmotor", name: "T03", fob: "$7,100 – $10,000", battery: "41.3 kWh", batteryType: "LFP", range: "403 km", charging: "Stellantis-backed + European standards + dual 8\"+10\" screens", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/T03/T03%20display.png", status: "factory", statusText: "Factory Order: 14 Days", link: "/products/revenue-king/leapmotor-t03", tags: ["Hatchback (Sub-Compact)", "LFP (Lithium Iron Phosphate)", "300 km - 450 km", "Under $15,000", "LHD (Left-Hand Drive)", "Factory Order (14+ Days)"] },
];

const specLabels: Record<string, string> = {
  "38.8 kWh": "Battery", "44.9 kWh": "Battery", "57.6 kWh": "Battery", "55.1 kWh": "Battery", "60.0 kWh": "Battery", "51.9 kWh": "Battery", "37.9 kWh": "Battery", "27.9 kWh": "Battery", "70.0 kWh": "Battery", "41.3 kWh": "Battery",
  "405 km": "Range (NEDC)", "420 km": "Range (NEDC)", "510 km": "Range (NEDC)", "520 km": "Range (NEDC)", "530 km": "Range (NEDC)", "430 km": "Range (NEDC)", "301 km": "Range (NEDC)", "550 km": "Range (NEDC)", "403 km": "Range (NEDC)",
  "Global #1 commuter — Blade Battery + rotating touchscreen + mature 3-electric system": "Buyer Logic",
  "2025 comfort suspension — e-Platform 3.0 + heat pump across all trims": "Buyer Logic",
  "1M+ units validated — ultra-low drag + large boot + lowest after-sales costs": "Buyer Logic",
  "[2025 New King] LiDAR smart driving + executive rear legroom + 400V fast charge": "Buyer Logic",
  "[Battle-Tested] Shield Short-Blade battery + Galaxy OS + global safety design": "Buyer Logic",
  "Box design + wide-opening doors + camping-friendly": "Buyer Logic",
  "Retro design + 510 km range + effortless driving": "Buyer Logic",
  "Premium quality at entry price — high-strength steel + flexible charging": "Buyer Logic",
  "ME bestseller — exceptional real-world range + extreme heat optimised": "Buyer Logic",
  "Stellantis-backed + European standards + dual 8\"+10\" screens": "Buyer Logic",
};

export { vehicles, specLabels };
