const vehicles = [
  {
    brand: "AITO",
    name: "M9 (问界)",
    fob: "CNY 469,800 – 589,800",
    battery: "100 kWh",
    batteryType: "NCM / EREV",
    range: "1,400 km (Ext)",
    charging: "[China's Tech Pinnacle] Huawei ADS 3.0 — projection headlights + Turing chassis + full Huawei ecosystem",
    img: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 28 Days",
    tags: ["Premium SUV", "NCM (Ternary Lithium)", "700 km +", "Above CNY 450,000", "EREV (Extended Range)", "Factory Order (21+ Days)"],
  },
  {
    brand: "Geely",
    name: "Galaxy M9",
    fob: "CNY 209,800 – 259,800",
    battery: "60.0 kWh",
    batteryType: "LFP",
    range: "1,500 km (Ext)",
    charging: "[Value Bombshell] Only air suspension + tri-motor AWD in class — 5.2m full-size 6-seat SUV + AI cockpit",
    img: "https://images.unsplash.com/photo-1563720360172-67b8f3dce741?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 21 Days",
    tags: ["Premium SUV", "LFP Blade (BYD)", "700 km +", "CNY 250,000 - CNY 350,000", "EREV (Extended Range)", "Factory Order (21+ Days)"],
  },
  {
    brand: "BYD",
    name: "Sealion 7 (海狮)",
    fob: "CNY 189,800 – 239,800",
    battery: "82.5 kWh",
    batteryType: "LFP",
    range: "610 km",
    charging: "[2025 Flagship SUV] e-Platform 3.0 Evo — 23,000 rpm motor + dual-gun fast charge + global flagship",
    img: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Shenzhen",
    tags: ["Premium SUV", "LFP Blade (BYD)", "500 km - 700 km", "CNY 250,000 - CNY 350,000", "800V Platform", "In Stock (Port)"],
  },
  {
    brand: "Hongqi",
    name: "E-HS9",
    fob: "CNY 589,800 – 779,800",
    battery: "120 kWh",
    batteryType: "NCM",
    range: "510 km",
    charging: "\"China's Rolls-Royce\" — unparalleled presence · air suspension + opulent interior · ME & Central Asia status symbol",
    img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 35 Days",
    tags: ["Premium SUV", "NCM (Ternary Lithium)", "500 km - 700 km", "Above CNY 450,000", "800V Platform", "Factory Order (21+ Days)"],
  },
  {
    brand: "Stelato",
    name: "S9 (享界)",
    fob: "CNY 399,800 – 449,800",
    battery: "100 kWh",
    batteryType: "NCM",
    range: "800 km",
    charging: "[Huawei Flagship Sedan] Rivals S-Class — zero-gravity rear seats + privacy screen + ADS advanced autonomy",
    img: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 30 Days",
    tags: ["Executive Sedan", "NCM (Ternary Lithium)", "700 km +", "CNY 350,000 - CNY 450,000", "800V Platform", "Factory Order (21+ Days)"],
  },
  {
    brand: "Zeekr",
    name: "001 (2025款)",
    fob: "CNY 269,000 – 329,000",
    battery: "100 kWh",
    batteryType: "NCM / LFP",
    range: "750 km",
    charging: "Full-range 800V + LiDAR — ultra-fast charging + in-house motor + top-tier shooting brake design",
    img: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Shanghai",
    tags: ["Executive Sedan", "NCM (Ternary Lithium)", "700 km +", "CNY 350,000 - CNY 450,000", "800V Platform", "In Stock (Port)"],
  },
  {
    brand: "Xiaomi",
    name: "SU7 Ultra",
    fob: "CNY 529,900",
    battery: "101 kWh",
    batteryType: "NCM",
    range: "630 km",
    charging: "Performance social currency — 1,500+ hp + carbon-fibre aero kit + full Xiaomi ecosystem",
    img: "https://images.unsplash.com/photo-1606611013016-969c19ba27a5?auto=format&fit=crop&w=800&q=80",
    status: "factory",
    statusText: "Factory Order: 35 Days",
    tags: ["Executive Sedan", "NCM (Ternary Lithium)", "500 km - 700 km", "Above CNY 450,000", "800V Platform", "Factory Order (21+ Days)"],
  },
  {
    brand: "XPENG",
    name: "G9 (2025款)",
    fob: "CNY 263,900 – 359,900",
    battery: "98.0 kWh",
    batteryType: "NCM / LFP",
    range: "702 km",
    charging: "800V smart-driving benchmark — SiC platform + Dynaudio cabin · strong rep in Nordics & SE Asia",
    img: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Guangzhou",
    tags: ["Premium SUV", "NCM (Ternary Lithium)", "700 km +", "CNY 350,000 - CNY 450,000", "800V Platform", "In Stock (Port)"],
  },
  {
    brand: "BYD",
    name: "Seal (海豹 2025)",
    fob: "CNY 179,800 – 249,800",
    battery: "82.5 kWh",
    batteryType: "LFP",
    range: "700 km",
    charging: "LiDAR + 800V fast charge — CTB technology + DiPilot 300 · looks great, drives better, charges faster",
    img: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Shenzhen",
    tags: ["Executive Sedan", "LFP Blade (BYD)", "700 km +", "CNY 250,000 - CNY 350,000", "800V Platform", "In Stock (Port)"],
  },
  {
    brand: "Li Auto",
    name: "L6 (理想)",
    fob: "CNY 249,800 – 279,800",
    battery: "36.8 kWh",
    batteryType: "LFP (EREV)",
    range: "1,390 km (Ext)",
    charging: "[Safest EREV Bet] China's #1 luxury EREV SUV 2024 — TV + fridge + sofa · 60% cheaper to run than ICE rivals",
    img: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    status: "in-stock",
    statusText: "In Stock: Beijing",
    tags: ["Premium SUV", "LFP Blade (BYD)", "700 km +", "CNY 250,000 - CNY 350,000", "EREV (Extended Range)", "In Stock (Port)"],
  },
];

const specLabels: Record<string, string> = {
  "100 kWh": "Battery",
  "60.0 kWh": "Battery",
  "82.5 kWh": "Battery",
  "120 kWh": "Battery",
  "101 kWh": "Battery",
  "98.0 kWh": "Battery",
  "36.8 kWh": "Battery",
  "1,400 km (Ext)": "Range (Extended)",
  "1,500 km (Ext)": "Range (Extended)",
  "610 km": "Range (CLTC)",
  "510 km": "Range (CLTC)",
  "800 km": "Range (CLTC)",
  "750 km": "Range (CLTC)",
  "630 km": "Range (CLTC)",
  "702 km": "Range (CLTC)",
  "700 km": "Range (CLTC)",
  "1,390 km (Ext)": "Range (Extended)",
  "[China's Tech Pinnacle] Huawei ADS 3.0 — projection headlights + Turing chassis + full Huawei ecosystem": "Buyer Logic",
  "[Value Bombshell] Only air suspension + tri-motor AWD in class — 5.2m full-size 6-seat SUV + AI cockpit": "Buyer Logic",
  "[2025 Flagship SUV] e-Platform 3.0 Evo — 23,000 rpm motor + dual-gun fast charge + global flagship": "Buyer Logic",
  "\"China's Rolls-Royce\" — unparalleled presence · air suspension + opulent interior · ME & Central Asia status symbol": "Buyer Logic",
  "[Huawei Flagship Sedan] Rivals S-Class — zero-gravity rear seats + privacy screen + ADS advanced autonomy": "Buyer Logic",
  "Full-range 800V + LiDAR — ultra-fast charging + in-house motor + top-tier shooting brake design": "Buyer Logic",
  "Performance social currency — 1,500+ hp + carbon-fibre aero kit + full Xiaomi ecosystem": "Buyer Logic",
  "800V smart-driving benchmark — SiC platform + Dynaudio cabin · strong rep in Nordics & SE Asia": "Buyer Logic",
  "LiDAR + 800V fast charge — CTB technology + DiPilot 300 · looks great, drives better, charges faster": "Buyer Logic",
  "[Safest EREV Bet] China's #1 luxury EREV SUV 2024 — TV + fridge + sofa · 60% cheaper to run than ICE rivals": "Buyer Logic",
};

export { vehicles, specLabels };
