const vehicles = [
  { brand: "AITO", name: "M9 (问界)", fob: "$67,100 – $84,300", battery: "100 kWh", batteryType: "NCM / EREV", range: "1,400 km (Ext)", charging: "[China's Tech Pinnacle] Huawei ADS 3.0 — projection headlights + Turing chassis + full Huawei ecosystem", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/M9/M9%20display.webp", status: "factory", statusText: "Factory Order: 28 Days", link: "/products/elite-flagship/aito-m9", tags: ["Premium SUV", "NCM (Ternary Lithium)", "700 km +", "Above $65,000", "EREV (Extended Range)", "Factory Order (21+ Days)"] },
  { brand: "Geely", name: "Galaxy M9", fob: "$30,000 – $37,100", battery: "60.0 kWh", batteryType: "LFP", range: "1,500 km (Ext)", charging: "[Value Bombshell] Only air suspension + tri-motor AWD in class — 5.2m full-size 6-seat SUV + AI cockpit", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/Galaxym9/Galaxym9%20display.jpg", status: "factory", statusText: "Factory Order: 21 Days", link: "/products/elite-flagship/geely-galaxy-m9", tags: ["Premium SUV", "LFP Blade (BYD)", "700 km +", "$35,000 - $50,000", "EREV (Extended Range)", "Factory Order (21+ Days)"] },
  { brand: "BYD", name: "Sealion 7 (海狮)", fob: "$27,100 – $34,300", battery: "82.5 kWh", batteryType: "LFP", range: "610 km", charging: "[2025 Flagship SUV] e-Platform 3.0 Evo — 23,000 rpm motor + dual-gun fast charge + global flagship", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/sealion/sealion%20display.webp", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/elite-flagship/byd-sealion-7", tags: ["Premium SUV", "LFP Blade (BYD)", "500 km - 700 km", "$35,000 - $50,000", "800V Platform", "In Stock (Port)"] },
  { brand: "Hongqi", name: "E-HS9", fob: "$84,300 – $111,400", battery: "120 kWh", batteryType: "NCM", range: "510 km", charging: "\"China's Rolls-Royce\" — unparalleled presence · air suspension + opulent interior · ME & Central Asia status symbol", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/E-HS9/E-HS9%20display.jpg", status: "factory", statusText: "Factory Order: 35 Days", link: "/products/elite-flagship/hongqi-e-hs9", tags: ["Premium SUV", "NCM (Ternary Lithium)", "500 km - 700 km", "Above $65,000", "800V Platform", "Factory Order (21+ Days)"] },
  { brand: "Stelato", name: "S9 (享界)", fob: "$57,100 – $64,300", battery: "100 kWh", batteryType: "NCM", range: "800 km", charging: "[Huawei Flagship Sedan] Rivals S-Class — zero-gravity rear seats + privacy screen + ADS advanced autonomy", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/S9/S9%20display.png", status: "factory", statusText: "Factory Order: 30 Days", link: "/products/elite-flagship/stelato-s9", tags: ["Executive Sedan", "NCM (Ternary Lithium)", "700 km +", "$50,000 - $65,000", "800V Platform", "Factory Order (21+ Days)"] },
  { brand: "Zeekr", name: "001 (2025款)", fob: "$38,400 – $47,000", battery: "100 kWh", batteryType: "NCM / LFP", range: "750 km", charging: "Full-range 800V + LiDAR — ultra-fast charging + in-house motor + top-tier shooting brake design", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/001/001%20display.png", status: "in-stock", statusText: "In Stock: Shanghai", link: "/products/elite-flagship/zeekr-001", tags: ["Executive Sedan", "NCM (Ternary Lithium)", "700 km +", "$50,000 - $65,000", "800V Platform", "In Stock (Port)"] },
  { brand: "Xiaomi", name: "SU7 Ultra", fob: "$75,700", battery: "101 kWh", batteryType: "NCM", range: "630 km", charging: "Performance social currency — 1,500+ hp + carbon-fibre aero kit + full Xiaomi ecosystem", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/SU7ultra/SU7ultra%20display.png", status: "factory", statusText: "Factory Order: 35 Days", link: "/products/elite-flagship/xiaomi-su7-ultra", tags: ["Executive Sedan", "NCM (Ternary Lithium)", "500 km - 700 km", "Above $65,000", "800V Platform", "Factory Order (21+ Days)"] },
  { brand: "XPENG", name: "G9 (2025款)", fob: "$37,700 – $51,400", battery: "98.0 kWh", batteryType: "NCM / LFP", range: "702 km", charging: "800V smart-driving benchmark — SiC platform + Dynaudio cabin · strong rep in Nordics & SE Asia", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/XpengG9/XpengG9%20display.jpg", status: "in-stock", statusText: "In Stock: Guangzhou", link: "/products/elite-flagship/xpeng-g9", tags: ["Premium SUV", "NCM (Ternary Lithium)", "700 km +", "$50,000 - $65,000", "800V Platform", "In Stock (Port)"] },
  { brand: "BYD", name: "Seal (海豹 2025)", fob: "$25,700 – $35,700", battery: "82.5 kWh", batteryType: "LFP", range: "700 km", charging: "LiDAR + 800V fast charge — CTB technology + DiPilot 300 · looks great, drives better, charges faster", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/seal/seal%20display.webp", status: "in-stock", statusText: "In Stock: Shenzhen", link: "/products/elite-flagship/byd-seal", tags: ["Executive Sedan", "LFP Blade (BYD)", "700 km +", "$35,000 - $50,000", "800V Platform", "In Stock (Port)"] },
  { brand: "Li Auto", name: "L6 (理想)", fob: "$35,700 – $40,000", battery: "36.8 kWh", batteryType: "LFP (EREV)", range: "1,390 km (Ext)", charging: "[Safest EREV Bet] China's #1 luxury EREV SUV 2024 — TV + fridge + sofa · 60% cheaper to run than ICE rivals", img: "https://6a0327d1fc46b5b25f3480d6.imgix.net/L6/L6%20display.jpeg", status: "in-stock", statusText: "In Stock: Beijing", link: "/products/elite-flagship/li-auto-l6", tags: ["Premium SUV", "LFP Blade (BYD)", "700 km +", "$35,000 - $50,000", "EREV (Extended Range)", "In Stock (Port)"] },
];

const specLabels: Record<string, string> = {
  "100 kWh": "Battery", "60.0 kWh": "Battery", "82.5 kWh": "Battery", "120 kWh": "Battery", "101 kWh": "Battery", "98.0 kWh": "Battery", "36.8 kWh": "Battery",
  "1,400 km (Ext)": "Range (Extended)", "1,500 km (Ext)": "Range (Extended)", "610 km": "Range (CLTC)", "510 km": "Range (CLTC)", "800 km": "Range (CLTC)", "750 km": "Range (CLTC)", "630 km": "Range (CLTC)", "702 km": "Range (CLTC)", "700 km": "Range (CLTC)", "1,390 km (Ext)": "Range (Extended)",
  "[China's Tech Pinnacle] Huawei ADS 3.0 — projection headlights + Turing chassis + full Huawei ecosystem": "Buyer Logic",
  "[Value Bombshell] Only air suspension + tri-motor AWD in class — 5.2m full-size 6-seat SUV + AI cockpit": "Buyer Logic",
  "[2025 Flagship SUV] e-Platform 3.0 Evo — 23,000 rpm motor + dual-gun fast charge + global flagship": "Buyer Logic",
  "\"China's Rolls-Royce\" — unparalleled presence · air suspension + opulent interior · ME & Central Asia status symbol": "Buyer Logic",
  "[Huawei Flagship Sedan] Rivals S-Class — zero-gravity rear seats + privacy screen + ADS advanced autonomy": "Buyer Logic",
  "Full-range 800V + LiDAR — ultra-fast charging + in-house motor + top-tier shooting brake design": "Buyer Logic",
  "Performance social currency — 1,500+ hp + carbon-fibre aero kit + full Xiaomi ecosystem": "Buyer Logic",
  "800V smart-driving benchmark — SiC platform + Dynaudio cabin · strong rep in Nordics & SE Asia": "Buyer Logic",
  "LiDAR + 800V fast charge — CTB technology + DiPilot 300 · looks great, drives better, charges faster": "Buyer Logic",
  "[Safest EREV Bet] China's #1 luxury EREV SUV 2024 — TV + fridge + sofa · 60% cheaper to run than ICE rivals": "Buyer Logic",
};

export { vehicles, specLabels };
