import VehicleDetail from "../../_VehicleDetail";

const data = {
  vehicle: {
    brand: "Hongqi",
    name: "E-HS9",
    fob: "CNY 589,800 – 779,800",
    battery: "120 kWh",
    batteryType: "NCM",
    range: "510 km",
    charging: "\"China's Rolls-Royce\" — unparalleled presence · air suspension + opulent interior · ME & Central Asia status symbol",
    img: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80",
    status: "factory",
    statusText: "Factory Order: 35 Days",
  },
  category: "elite-flagship" as const,
  title: "Hongqi E-HS9",
  subtitle: "China's Rolls-Royce",
  heroDesc: "Unmatched road presence with Hongqi's flagship DNA. Air suspension, opulent 4-seat configuration, and the strongest status signal in Middle East and Central Asian markets.",
  stat1Label: "km Range",
  stat1Value: "690",
  stat2Label: "Monthly Saving",
  stat2Value: "CNY 3,500",
  stat3Label: "4/6/7",
  stat3Value: "Seats",
  whyTitle: "Why It Sells",
  whyDesc: "Presence that commands respect. The ultimate status mobile.",
  features: [
    { icon: "👑", title: "Unmatched Road Presence", desc: "5.2m length with Hongqi's iconic vertical grille. No other vehicle commands this level of visual authority in emerging luxury markets." },
    { icon: "🛋️", title: "4-Seat Executive Configuration", desc: "Individual rear captain's chairs with massage, ventilation, heating, and electric ottomans. Rear-seat entertainment screens and champagne chiller." },
    { icon: "🏗️", title: "Air Suspension Standard", desc: "Active air suspension with continuous damping control. Absorbs broken roads effortlessly — essential for emerging-market luxury travel." },
  ],
  specsLeft: [
    { label: "Vehicle Class", value: "Full-Size Luxury SUV" },
    { label: "Range (NEDC)", value: "690 km" },
    { label: "Battery Capacity", value: "120 kWh" },
    { label: "Battery Type", value: "NCM (CATL)" },
    { label: "Motor Power", value: "405 kW (551 hp)" },
    { label: "Drive Type", value: "Dual Motor AWD" },
    { label: "0 – 100 km/h", value: "5.0 sec" },
    { label: "Top Speed", value: "200 km/h" },
    { label: "DC Fast Charge", value: "~30 min" },
    { label: "Energy Density", value: "206 Wh/kg" },
  ],
  specsRight: [
    { label: "Suspension", value: "Air + Adaptive" },
    { label: "Warranty", value: "4 Yrs / 100,000 km" },
    { label: "Dimensions (L×W×H)", value: "5,209 × 2,010 × 1,731 mm" },
    { label: "Wheelbase", value: "3,110 mm" },
    { label: "Boot Volume", value: "350-760 L" },
    { label: "Seating", value: "4 / 6 / 7 Seats" },
    { label: "Audio", value: "BOSE Premium" },
    { label: "Ambient Light", value: "253 Colours" },
    { label: "Airbags", value: "8" },
  ],
  fits: [
    { icon: "👑", title: "Royal & Diplomatic", desc: "The standard for state occasions in multiple Belt & Road countries. The vehicle that says 'serious business'.", accent: "State-level presence" },
    { icon: "🏨", title: "Luxury Hotel Fleet", desc: "Define your 5-star hotel's arrival experience. The E-HS9 makes every guest feel like a head of state.", accent: "5-star standard" },
    { icon: "💎", title: "Private Collector", desc: "Limited production and iconic Hongqi heritage make this a genuine collector's piece that appreciates in cultural value.", accent: "Collector's item" },
  ],
  relatedModels: [
    { name: "AITO M9", href: "/products/elite-flagship/aito-m9" },
    { name: "Stelato S9", href: "/products/elite-flagship/stelato-s9" },
    { name: "Li Auto L6", href: "/products/elite-flagship/li-auto-l6" },
    { name: "Zeekr 001", href: "/products/elite-flagship/zeekr-001" },
  ],
  tags: ["Premium SUV", "Ultra Luxury"],
  galleryImages: [
    { src: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80", cat: "Exterior", label: "Front View" },
    { src: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1200&q=80", cat: "Exterior", label: "Side Profile" },
    { src: "https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80", cat: "Interior", label: "Executive Cabin" },
    { src: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80", cat: "Interior", label: "Rear Seats" },
  ],
  batchLevels: [
    { units: 5, display: "CNY 875K – CNY 1.15M" },
    { units: 10, display: "CNY 1.75M – CNY 2.30M" },
    { units: 20, display: "CNY 3.50M – CNY 4.60M" },
    { units: 50, display: "CNY 8.75M – CNY 11.5M" },
  ],
  batchMargin: { low: "CNY 175,000", high: "CNY 230,000" },
};

export default function Page() {
  return <VehicleDetail data={data} />;
}
